all:
	javac src/BomberGame/BomberMap.java
	javac src/BomberGame/MapCell.java
	javac src/BomberGame/MovingObject.java
	javac src/BomberGame/Blank_c.java
	javac src/BomberGame/Bomb_c.java
	javac src/BomberGame/BomberMan.java
	javac src/BomberGame/Box_c.java
	javac src/BomberGame/Flame_c.java
	javac src/BomberGame/Wall_c.java
	javac src/BomberGame/Well_c.java
	javac src/BomberGame/ObjectPool.java
	javac src/BomberGame/GameController.java
	javac src/BomberInit/BomberKeyConfig.java
	javac src/BomberInit/BomberMapMake.java
	javac src/Button_ex.java
	javac src/Main.java
